name: Manual Python Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the script in'
        required: true
        default: 'development'
  push:
    branches:
      - master  # or 'master', or any branch you want

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Run Python script
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: python day1/testenv.py
