name: Matrix Environments CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-python-in-environments:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env_name: [dev, test, prod]
        python-version: [3.13.2]

    env:
      ENV_NAME: ${{ matrix.env_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f day1/requirements.txt ]; then pip install -r day1/requirements.txt; fi

      - name: Run Python Script for ${{ matrix.env_name }} environment
        run: |
          echo "Running in environment: $ENV_NAME"
          python day1/envtestmatrix.py $ENV_NAME

