name: Pull Request Checks

on:
  pull_request:
    branches:
      - master        # Target branch of the PR
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: payrolldb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: payrolldb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r payrollapplication/requirements.txt

      - name: Wait for DB
        run: |
          until pg_isready -h localhost -p 5432; do echo "Waiting for DB..."; sleep 1; done

      - name: Run migrations
        run: python payrollapplication//manage.py migrate

      - name: Run tests
        run: python payrollapplication/manage.py test
